name: Evercode checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/PasswordValidationReactTests/App.test.js -o src/App.test.js

      - name: Yarn test
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test